#ifdef PICOUTIL_SIZEOF_FLOAT16
    #undef PICOUTIL_SIZEOF_FLOAT16
#endif
#ifdef PICOUTIL_SIZEOF_FLOAT
    #undef PICOUTIL_SIZEOF_FLOAT
#endif
#ifdef PICOUTIL_SIZEOF_DOUBLE
    #undef PICOUTIL_SIZEOF_DOUBLE
#endif
#ifdef PICOUTIL_SIZEOF_LONG_DOUBLE
    #undef PICOUTIL_SIZEOF_LONG_DOUBLE
#endif

#define PICOUTIL_SIZEOF_FLOAT16 2U
#define PICOUTIL_SIZEOF_FLOAT 4U
#define PICOUTIL_SIZEOF_DOUBLE 8U
#define PICOUTIL_SIZEOF_LONG_DOUBLE 8U
