#ifndef PICOUTIL_VERSION_H
#define PICOUTIL_VERSION_H

#ifdef PICOUTIL_VERSION_MAJOR
    #undef PICOUTIL_VERSION_MAJOR
    #warning "PICOUTIL_VERSION_MAJOR shall not be defined"
#endif
#ifdef PICOUTIL_VERSION_MINOR
    #undef PICOUTIL_VERSION_MINOR
    #warning "PICOUTIL_VERSION_MINOR shall not be defined"
#endif
#ifdef PICOUTIL_VERSION_PATCH
    #undef PICOUTIL_VERSION_PATCH
    #warning "PICOUTIL_VERSION_PATCH shall not be defined"
#endif
#ifdef PICOUTIL_VERSION
    #undef PICOUTIL_VERSION
    #warning "PICOUTIL_VERSION shall not be defined"
#endif
#ifdef PICOUTIL_VERSION_STRING
    #undef PICOUTIL_VERSION_STRING
    #warning "PICOUTIL_VERSION_STRING shall not be defined"
#endif

#define PICOUTIL_VERSION_MAJOR 0
#define PICOUTIL_VERSION_MINOR 1
#define PICOUTIL_VERSION_PATCH 0
#define PICOUTIL_VERSION CHAOS_PP_PUSH(PICOUTIL_VERSION_MAJOR, CHAOS_PP_PUSH(., CHAOS_PP_PUSH(PICOUTIL_VERSION_MINOR, CHAOS_PP_PUSH(., PICOUTIL_VERSION_PATCH))))
#define PICOUTIL_VERSION_STRING CHAOS_PP_STRINGIZE(PICOUTIL_VERSION)

#endif